/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package grademaster.views.panels.navbar;

import grademaster.utils.WindowFunctions;
import grademaster.views.panels.content.principal.SubjectsPrincipalView;
import grademaster.views.panels.content.principal.UsersPrincipalView;
import grademaster.views.panels.content.principal.YearListPrincipalView;
import grademaster.views.panels.content.teacher.gradesTeacherView;


/**
 *
 * @author Jesus24-Dev
 */
public class PrincipalNavbar extends javax.swing.JPanel {

    
    public static YearListPrincipalView yearListPrincipalView;
    public static UsersPrincipalView usersPrincipalView;
    public static gradesTeacherView grades_teacher_view;
    public static SubjectsPrincipalView subjectsPrincipalView;
            
    public PrincipalNavbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usersPrincipalButton = new javax.swing.JButton();
        listPrincipalButton = new javax.swing.JButton();
        gradePrincipalButton = new javax.swing.JButton();
        subjectsPrincipalButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        usersPrincipalButton.setBackground(new java.awt.Color(255, 255, 255));
        usersPrincipalButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        usersPrincipalButton.setForeground(new java.awt.Color(0, 0, 0));
        usersPrincipalButton.setText("Users");
        usersPrincipalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersPrincipalButtonActionPerformed(evt);
            }
        });

        listPrincipalButton.setBackground(new java.awt.Color(255, 255, 255));
        listPrincipalButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        listPrincipalButton.setForeground(new java.awt.Color(0, 0, 0));
        listPrincipalButton.setText("Year Lists");
        listPrincipalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPrincipalButtonActionPerformed(evt);
            }
        });

        gradePrincipalButton.setBackground(new java.awt.Color(255, 255, 255));
        gradePrincipalButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        gradePrincipalButton.setForeground(new java.awt.Color(0, 0, 0));
        gradePrincipalButton.setText("Grades");
        gradePrincipalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradePrincipalButtonActionPerformed(evt);
            }
        });

        subjectsPrincipalButton.setBackground(new java.awt.Color(255, 255, 255));
        subjectsPrincipalButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        subjectsPrincipalButton.setForeground(new java.awt.Color(0, 0, 0));
        subjectsPrincipalButton.setText("Subjects");
        subjectsPrincipalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectsPrincipalButtonActionPerformed(evt);
            }
        });

        signOutButton.setBackground(new java.awt.Color(255, 255, 255));
        signOutButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(0, 0, 0));
        signOutButton.setText("Sign out");
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(signOutButton)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersPrincipalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listPrincipalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradePrincipalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectsPrincipalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(usersPrincipalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listPrincipalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(gradePrincipalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subjectsPrincipalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(signOutButton)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usersPrincipalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersPrincipalButtonActionPerformed
        usersPrincipalView = new UsersPrincipalView();
        WindowFunctions.changeContent(usersPrincipalView);
    }//GEN-LAST:event_usersPrincipalButtonActionPerformed

    private void gradePrincipalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradePrincipalButtonActionPerformed
        grades_teacher_view = new gradesTeacherView();
        WindowFunctions.changeContent(grades_teacher_view);
    }//GEN-LAST:event_gradePrincipalButtonActionPerformed

    private void listPrincipalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPrincipalButtonActionPerformed
        yearListPrincipalView = new YearListPrincipalView();
        WindowFunctions.changeContent(yearListPrincipalView);
    }//GEN-LAST:event_listPrincipalButtonActionPerformed

    private void subjectsPrincipalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectsPrincipalButtonActionPerformed
        subjectsPrincipalView = new SubjectsPrincipalView();
        WindowFunctions.changeContent(subjectsPrincipalView);
    }//GEN-LAST:event_subjectsPrincipalButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        WindowFunctions.closeWindow();
        WindowFunctions.startLogin();
    }//GEN-LAST:event_signOutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gradePrincipalButton;
    private javax.swing.JButton listPrincipalButton;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton subjectsPrincipalButton;
    private javax.swing.JButton usersPrincipalButton;
    // End of variables declaration//GEN-END:variables
}
