/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package grademaster.views.panels.content.principal;

/**
 *
 * @author Jesus24-Dev
 */
public class SubjectsPrincipalView extends javax.swing.JPanel {

    /**
     * Creates new form SubjectsPrincipalView
     */
    public SubjectsPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        subjectTeacherTable = new javax.swing.JTable();
        assignTeacherButton = new javax.swing.JButton();
        changeTeacherButton = new javax.swing.JButton();
        deleteAssignmentButton = new javax.swing.JButton();
        showSubjectsButton = new javax.swing.JButton();
        addSubjectButton = new javax.swing.JButton();
        deleteSubjectButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        subjectTeacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "LASTNAME", "SUBJECT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(subjectTeacherTable);
        if (subjectTeacherTable.getColumnModel().getColumnCount() > 0) {
            subjectTeacherTable.getColumnModel().getColumn(0).setResizable(false);
            subjectTeacherTable.getColumnModel().getColumn(1).setResizable(false);
            subjectTeacherTable.getColumnModel().getColumn(2).setResizable(false);
        }

        assignTeacherButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        assignTeacherButton.setText("Assign Teacher");
        assignTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTeacherButtonActionPerformed(evt);
            }
        });

        changeTeacherButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        changeTeacherButton.setText("Change teacher");
        changeTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeTeacherButtonActionPerformed(evt);
            }
        });

        deleteAssignmentButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        deleteAssignmentButton.setText("Delete Assignment");
        deleteAssignmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAssignmentButtonActionPerformed(evt);
            }
        });

        showSubjectsButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        showSubjectsButton.setText("Show subjects");
        showSubjectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSubjectsButtonActionPerformed(evt);
            }
        });

        addSubjectButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addSubjectButton.setText("Add new Subject");
        addSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectButtonActionPerformed(evt);
            }
        });

        deleteSubjectButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        deleteSubjectButton.setText("Delete subject");
        deleteSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSubjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAssignmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showSubjectsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(assignTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(changeTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(deleteAssignmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(showSubjectsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(addSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(deleteSubjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteAssignmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAssignmentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAssignmentButtonActionPerformed

    private void assignTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignTeacherButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignTeacherButtonActionPerformed

    private void changeTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeTeacherButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeTeacherButtonActionPerformed

    private void showSubjectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSubjectsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showSubjectsButtonActionPerformed

    private void deleteSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSubjectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteSubjectButtonActionPerformed

    private void addSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSubjectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectButton;
    private javax.swing.JButton assignTeacherButton;
    private javax.swing.JButton changeTeacherButton;
    private javax.swing.JButton deleteAssignmentButton;
    private javax.swing.JButton deleteSubjectButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showSubjectsButton;
    private javax.swing.JTable subjectTeacherTable;
    // End of variables declaration//GEN-END:variables
}
